;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/Tin/Content/Localization/Tin
DestinationPath=Mods/GameFeatures/Tin/Content/Localization/Tin
ManifestName=Tin.manifest
ArchiveName=Tin.archive
CulturesToGenerate=cs
CulturesToGenerate=en
CulturesToGenerate=ja
CulturesToGenerate=pl
CulturesToGenerate=ru
CulturesToGenerate=zh
CulturesToGenerate=de

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationReport
bWordCountReport=true
WordCountReportName=Tin.csv

